parameters:
  variables: {}
  matrix: {}

jobs:
- job: ''

  variables: ${{ parameters.default }}
  strategy:
    matrix: ${{ parameters.matrix }}

  pool:
    vmImage: $(imageName)

  # Inspired by https://github.com/tokio-rs/tokio/blob/master/ci/azure-install-rust.yml
  steps:
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain none
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: 'Install Rust (Windows)'
    condition: eq(variables['Agent.OS'], 'Windows_NT')

  - bash: |
      set -o errexit; set -o pipefail; set -o nounset; set -o xtrace;
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: 'Install Rust (Darwin)'
    condition: eq(variables['Agent.OS'], 'Darwin')

  - bash: |
      set -o errexit; set -o pipefail; set -o nounset; set -o xtrace;
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      sudo apt-get install -y gcc-multilib
    displayName: 'Install Rust (Linux)'
    condition: eq(variables['Agent.OS'], 'Linux')

  - bash: |
      set -o errexit; set -o pipefail; set -o nounset; set -o xtrace;
      for TOOLCHAIN in $RUST_TOOLCHAIN; do (
        rustup toolchain install $TOOLCHAIN
        for TARGET in $RUST_TARGET_CHECK $RUST_TARGET_BUILD $RUST_TARGET_RUN; do [ "$TARGET" = $(rustup target list --toolchain $TOOLCHAIN | grep default | grep -o -e '^[^ ]\+') ] || rustup target add --toolchain $TOOLCHAIN "$TARGET"; done
        rustc +$TOOLCHAIN -Vv
        cargo +$TOOLCHAIN -V
      ); done
      rustup toolchain install $RUST_LINT_TOOLCHAIN
      rustup component add rustfmt --toolchain $RUST_LINT_TOOLCHAIN
      rustup component add clippy --toolchain $RUST_LINT_TOOLCHAIN
      for TARGET in $RUST_TARGET_CHECK $RUST_TARGET_BUILD $RUST_TARGET_RUN; do [ "$TARGET" = $(rustup target list --toolchain $TOOLCHAIN | grep default | grep -o -e '^[^ ]\+') ] || rustup target add --toolchain $RUST_LINT_TOOLCHAIN "$TARGET"; done
    displayName: Install Rust matrix

  - bash: |
      set -o errexit; set -o pipefail; set -o nounset; set -o xtrace;
      cargo +$RUST_LINT_TOOLCHAIN fmt -- --check
    displayName: Check formatting

  - bash: |
      set -o errexit; set -o pipefail; set -o nounset; set -o xtrace;
      for TOOLCHAIN in $RUST_TOOLCHAIN; do (
        export TOOLCHAIN
        OLD_IFS=$IFS IFS=";" RUST_FLAGS="$RUST_FLAGS;"; for RUSTFLAGS in $RUST_FLAGS; do ( IFS=$OLD_IFS
          export RUSTFLAGS
          OLD_IFS=$IFS IFS=";" RUST_FEATURES="$RUST_FEATURES;"; for FEATURES in $RUST_FEATURES; do ( IFS=$OLD_IFS
            [ "$FEATURES" = "all" ] && FEATURES="" ALL_FEATURES="--all-features" || ALL_FEATURES=""
            export FEATURES
            export ALL_FEATURES
            for TARGET in $RUST_TARGET_CHECK $RUST_TARGET_BUILD $RUST_TARGET_RUN; do (
              cargo +$RUST_LINT_TOOLCHAIN clippy --target "$TARGET" --all-targets --no-default-features --features "$FEATURES" $ALL_FEATURES -- -D warnings
            ); done
            for TARGET in $RUST_TARGET_BUILD $RUST_TARGET_RUN; do (
              cargo +$TOOLCHAIN build --verbose --target "$TARGET" --all-targets --no-default-features --features "$FEATURES" $ALL_FEATURES
              case "${TARGET%%-*}" in i386|i686|x86_64) RUSTFLAGS="$RUSTFLAGS -C target-cpu=native";; esac
              cargo +$TOOLCHAIN build --verbose --target "$TARGET" --all-targets --no-default-features --features "$FEATURES" $ALL_FEATURES --release
            ); done
            for TARGET in $RUST_TARGET_RUN; do (
              RUST_BACKTRACE=full cargo +$TOOLCHAIN test --target "$TARGET" --no-default-features --features "$FEATURES" $ALL_FEATURES
              RUSTFLAGS="$RUSTFLAGS -C target-cpu=native" RUST_BACKTRACE=full cargo +$TOOLCHAIN test --target "$TARGET" --no-default-features --features "$FEATURES" $ALL_FEATURES --release
              RUSTFLAGS="$RUSTFLAGS -C target-cpu=native" RUST_BACKTRACE=full cargo +$TOOLCHAIN bench --target "$TARGET" --no-default-features --features "$FEATURES" $ALL_FEATURES
              [ ! -d examples ] || for example in examples/*; do example=${example##*/}; (
                RUST_BACKTRACE=full cargo +$TOOLCHAIN run --target "$TARGET" --example ${example%.*} --no-default-features --features "$FEATURES" $ALL_FEATURES
                RUSTFLAGS="$RUSTFLAGS -C target-cpu=native" RUST_BACKTRACE=full cargo +$TOOLCHAIN run --target "$TARGET" --example ${example%.*} --no-default-features --features "$FEATURES" $ALL_FEATURES --release
              ); done
            ); done
          ); done; IFS=$OLD_IFS
        ); done; IFS=$OLD_IFS
      ); done
    displayName: Build & Run

  - bash: |
      set -o errexit; set -o pipefail; set -o nounset; set -o xtrace;
      for TARGET in $RUST_TARGET_CHECK $RUST_TARGET_BUILD $RUST_TARGET_RUN; do
        cargo +$RUST_LINT_TOOLCHAIN doc --no-deps --target "$TARGET" --all-features --release &>/dev/null
      done
    displayName: Check documentation
